Resources:
  App:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: RevisionBeanstalk
      Description: "Revision on Beanstalk"

  AppVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref App
      SourceBundle:
        S3Bucket: "revision-beanstalk-935529178062"
        S3Key: "source.zip"

  InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BeanstalkInstanceProfileRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: {Service: "ec2.amazonaws.com"}
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: BucketAccess
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                  - "s3:PutObject"
                Effect: "Allow"
                Resource: "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: revision-beanstalk-ip
      Roles:
        - !Ref InstanceProfileRole

  AppConfiguration:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref App
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-specific.html#command-options-nodejs
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalinglaunchconfiguration
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html#configuration-options-recommendedvalues
      OptionSettings:
#        - Namespace: "aws:elasticbeanstalk:environment:proxy"
#          OptionName: ProxyServer
#          Value: nginx
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: InstanceType
          Value: "t2.micro"
        - Namespace: "aws:elasticbeanstalk:container:php:phpini"
          OptionName: display_errors
          Value: "On"
        - Namespace: "aws:elasticbeanstalk:xray"
          OptionName: XRayEnabled
          Value: true
      #PlatformArn for custom platform
      SolutionStackName: "64bit Amazon Linux 2 v3.3.12 running PHP 8.0"

  # https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment.html
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref App
      EnvironmentName: RevisionBeanstalkEnvironment
      TemplateName: !Ref AppConfiguration
      VersionLabel: !Ref AppVersion
      Tier:
        Name: WebServer
        Type: Standard
