init:
	eb init --profile treezor-playground
create:
	eb create --profile treezor-playground --cname revisionbeanstalk1533 --instance-types t2.micro --min-instances 2 --elb-type application -- multi-ecs