Transform: AWS::Serverless-2016-10-31
Resources:
  StepMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StepFunctionRevisionExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: states.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      - arn:aws:iam::aws:policy/AmazonSQSFullAccess
      - arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess
      - arn:aws:iam::aws:policy/AmazonKinesisFullAccess
      - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
      - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
  StepMachineLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: revision-stepfunction-lambda
      Runtime: nodejs12.x
      MemorySize: 128
      CodeUri: s3://revision-935529178062-cloudformation/4dd6dda1497cd5db6dd2827138b1c336
      Handler: index.lambda
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSXRayDaemonWriteAccess
      Timeout: 6
      Tracing: Active
