Transform: AWS::Serverless-2016-10-31
Resources:

  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: revision-step-function
      AttributeDefinitions:
        - AttributeName: "CharacterName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "CharacterName"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  StepMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StepFunctionRevisionExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: "states.amazonaws.com" }
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
        - "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
        - "arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/AmazonKinesisFullAccess"
        - "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"
        - "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"

  StepMachineLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: revision-stepfunction-lambda
      Runtime: nodejs12.x
      MemorySize: 128
      CodeUri: ./src/lambda
      Handler: index.lambda
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      Timeout: 6
      Tracing: "Active"

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "RevisionStepFunctionQueue"

Outputs:
  QueueURL:
    Description: "URL Queue"
    Value: !Ref SQSQueue