<?php

namespace App\Command;

use App\Helper\ConsumedCapacityTrait;
use Aws\DynamoDb\DynamoDbClient;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

class EmptyTableCommand extends Command
{
    use ConsumedCapacityTrait;

    private Environment $twig;
    private DynamoDbClient $dynamoClient;

    public function __construct(string $name = null)
    {
        $this->twig = new Environment(new FilesystemLoader([__DIR__."/../template"]));
        $this->dynamoClient = new DynamoDbClient([
            'region' => 'eu-west-3',
            'version' => '2012-08-10',
        ]);
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName('empty-table');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $result = $this->dynamoClient->deleteItem([
            'TableName' => 'revision-dynamo',
            'Key' => [
                'CharacterName' => ['S' => 'Mario'],
            ],
            'ReturnConsumedCapacity' => 'INDEXES'
        ]);

        $this->showConsumeCapacity($result->toArray(), new SymfonyStyle($input, $output));

        return 0;
    }
}