<?php

namespace App\Command;


use App\Helper\ConsumedCapacityTrait;
use App\Table\ScanQueryDynamoItemTable;
use Aws\DynamoDb\DynamoDbClient;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class PartiqlCommand extends Command
{
    private DynamoDbClient $client;

    use ConsumedCapacityTrait;

    public function __construct(string $name = null)
    {
        $this->client = new DynamoDbClient([
            'region' => 'eu-west-3',
            'version' => '2012-08-10',
            'retries' => 3,
        ]);
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName("sql");
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $result = $this->client->executeStatement([
            'Statement' => 'SELECT * FROM "revision-dynamo"',
            'ReturnConsumedCapacity' => 'INDEXES',
        ]);

        $table = new ScanQueryDynamoItemTable($output);
        foreach($result["Items"] as $item) {
            $table->addDynamoItem($item);
        }

        $table->render();

        $this->showConsumeCapacity($result->toArray(), $output);

        return 0;
    }
}