<?php

namespace App\Command;

use App\Helper\ConsumedCapacityTrait;
use App\Table\ScanQueryDynamoItemTable;
use Aws\DynamoDb\DynamoDbClient;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

class QueryCommand extends Command
{
    use ConsumedCapacityTrait;

    private DynamoDbClient $dynamoClient;

    public function __construct(string $name = null)
    {
        $this->dynamoClient = new DynamoDbClient([
            'region' => 'eu-west-3',
            'version' => '2012-08-10',
            'retries' => 0,
        ]);
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName("query");
        $this->addOption('consistent-read', null, InputOption::VALUE_NONE);
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $symfonyStyle = new SymfonyStyle($input, $output);

        $result = $this->dynamoClient->query([
            'TableName' => 'revision-dynamo',
            'Select' => 'SPECIFIC_ATTRIBUTES',
            'ProjectionExpression' => 'truc',
            'KeyConditions' => [
                'CharacterName' => [
                    'ComparisonOperator' => 'EQ',
                    'AttributeValueList' => [['S' => 'Mario']]
                ]
            ],
            'ConsistentRead' =>  $input->getOption('consistent-read'),
            'ReturnConsumedCapacity' => 'INDEXES'
        ]);

        $table = new ScanQueryDynamoItemTable($output);
        $table->addDynamoItem($result['Items'][0]);
        $table->render();

        $this->showConsumeCapacity($result->toArray(), $symfonyStyle);


        return 0;
    }
}