<?php

namespace App\Command;

use App\Helper\ConsumedCapacityTrait;
use Aws\DynamoDb\DynamoDbClient;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

class QueryCommand extends Command
{
    use ConsumedCapacityTrait;

    private Environment $twig;
    private DynamoDbClient $dynamoClient;

    public function __construct(string $name = null)
    {
        $this->twig = new Environment(new FilesystemLoader([__DIR__."/../template"]));
        $this->dynamoClient = new DynamoDbClient([
            'region' => 'eu-west-3',
            'version' => '2012-08-10',
        ]);
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName("query");
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $symfonyStyle = new SymfonyStyle($input, $output);

        $output = $this->dynamoClient->query([
            'TableName' => 'revision-dynamo',
            'KeyConditions' => [
                'CharacterName' => [
                    'ComparisonOperator' => 'EQ',
                    'AttributeValueList' => [['S' => 'Samsung']]
                ]
            ],
            'ReturnConsumedCapacity' => 'INDEXES'
        ]);

       $this->showConsumeCapacity($output->toArray(), $symfonyStyle);


        return 0;
    }
}