<?php

namespace App\Command;

use App\Helper\ConsumedCapacityTrait;
use Aws\DynamoDb\DynamoDbClient;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class UpdateCommand extends Command
{
    use ConsumedCapacityTrait;

    private DynamoDbClient $dynamoClient;

    public function __construct(string $name = null)
    {
        $this->dynamoClient = new DynamoDbClient([
            'region' => 'eu-west-3',
            'version' => '2012-08-10',
            'retries' => 0,
        ]);
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName("update");
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $result = $this->dynamoClient->updateItem([
            "TableName" => "revision-dynamo",
            "Key" => [
                "CharacterName" => ["S" => "Mario"],
            ],
            "UpdateExpression" => "SET truc = :value",
            "ExpressionAttributeValues" => [
                ":value" => ["S" => "machin"],
            ],
            "ReturnValues" => "ALL_NEW",
            'ReturnConsumedCapacity' => "INDEXES",
        ]);

        dump($result);

        $this->showConsumeCapacity($result->toArray(), $output);

        return 0;
    }
}