version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/project-onpremise
  - source: /config/vhost.conf
    destination: /etc/apache2/sites-enabled/onpremise-codedeploy.local.conf
file_exists_behavior: OVERWRITE
permissions:
 - object: /var/www/html/project-onpremise
   pattern: "*"
   owner: www-data
   group: www-data
   mode: 777
   type:
    - file
hooks:
  # ApplicationStop > DownloadBundle > BeforeInstall > Install > AfterInstall > ApplicationStart > ValidateSErvice
  # BeforeBlockTraffic > BlockTraffic > AfterBlockTraffic
  # BeforeAllowTraffic > AllowTraffic > AfterAllowTraffic
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/templating.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/monitor.sh
      timeout: 300
      runas: root