# https://docs.aws.amazon.com/codepipeline/latest/userguide/integrations-action-type.html#integrations-deploy
Resources:
  AppPipelineBuild:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: codebuild.yaml

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

  AppPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: code-pipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: Allow
            Principal: { Service: [ "codepipeline.amazonaws.com" ] }
            Action: [ "sts:AssumeRole" ]
      Policies:
        - PolicyName: PassRole
          PolicyDocument: |
            {
                "Version": "2012-10-17", 
                "Statement": [ 
                    { 
                        "Effect": "Allow",
                        "Action": "iam:PassRole", 
                        "Resource": "arn:aws:iam::935529178062:role/CloudFormationRole"
                    }
                ] 
            }
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AWSCodePipelineFullAccess"
        - "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess"

  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: revision-codepipeline
      RoleArn: !GetAtt AppPipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: "codepipeline-source-935529178062"
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                S3Bucket: "codepipeline-source-935529178062"
                S3ObjectKey: "source.zip"
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: SourceBuild
              Configuration:
                ProjectName: revision-codebuild
        - Name: Release
          Actions:
            - Name: Release
              InputArtifacts:
                - Name: SourceBuild
              ActionTypeId:
                Category: Deploy # Source | Build | Test | Deploy | Invoke | Approval
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: "codepipeline-source-935529178062"
                Extract: false
                ObjectKey: "release.zip"
        - Name: WaitAnswer
          Actions:
            - Name: ManualAprove
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: "Manual"
                Version: 1
              Configuration:
                NotificationArn: "arn:aws:sns:eu-west-3:935529178062:EmailNotified"
        - Name: Deploy
          Actions:
            - Name: Deploy
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: lol
                TemplatePath: SourceOutput::template.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CloudFormationRole.Arn