# https://www.singlestoneconsulting.com/blog/aws-cloudformation-iac-at-enterprise-scale/#:~:text=CloudFormation%20Modules%20allow%20you%20to,Modules%20can%20be%20nested.
Resources:
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      ProtocolType: HTTP
      Name: revision-http
      CorsConfiguration:
        AllowHeaders:
          - ABC
        AllowMethods: ["GET", "POST"]
        AllowOrigins: ["*"]
        ExposeHeaders: ["ABC"]
        MaxAge: 123

  RouteHTTP:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: route-http.yaml
      Parameters:
        ApiId: !Ref ApiGateway
        ApiIntegrationRole: !GetAtt ApiGatewayIntegration.Arn

  RouteSQS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: route-sqs.yaml
      Parameters:
        ApiId: !Ref ApiGateway
        CredentialsArn: !GetAtt ApiGatewayIntegration.Arn

  RouteLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: route-lambda.yaml
      Parameters:
        ApiId: !Ref ApiGateway
        CredentialsArn: !GetAtt ApiGatewayIntegration.Arn

  RouteEventBridge:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: route-event-bridge.yaml
      Parameters:
        ApiId: !Ref ApiGateway
        CredentialsArn: !GetAtt ApiGatewayIntegration.Arn

  RouteKinesis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: route-kinesis.yaml
      Parameters:
        ApiId: !Ref ApiGateway
        CredentialsArn: !GetAtt ApiGatewayIntegration.Arn

  RouteStepFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: route-step-function.yaml
      Parameters:
        ApiId: !Ref ApiGateway
        CredentialsArn: !GetAtt ApiGatewayIntegration.Arn

  ApiGatewayIntegration:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: "apigateway.amazonaws.com" }
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
        - "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
        - "arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess"
        - "arn:aws:iam::aws:policy/AmazonKinesisFullAccess"
        - "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"

  ApiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      AutoDeploy: true
      Description: prod
      StageName: $default
      DefaultRouteSettings:
        # The burst limit defines the number of requests your API can handle concurrently. The rate limit defines the number of allowed requests per second.
        DetailedMetricsEnabled: false
        ThrottlingBurstLimit: 1
        ThrottlingRateLimit: 1

  ApiGatewayDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: 'flow.playground.treezor.co.'
      Comment: 'http revision subdomain'
      Name: 'http-revision.flow.playground.treezor.co'
      Type: CNAME
      TTL: 60
      ResourceRecords:
        - "www.google.com"

  ApiGatewayACM:
    DependsOn: ApiGatewayDNSRecord
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "http-revision.flow.playground.treezor.co"
      ValidationMethod: "DNS"

  ApiGatewayDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: "http-revision.flow.playground.treezor.co"
      DomainNameConfigurations:
        - EndpointType: Regional
          CertificateArn: !Ref ApiGatewayACM

  ApiGatewayApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref ApiGateway
      DomainName: "http-revision.flow.playground.treezor.co"
      Stage: !Ref ApiGatewayStage

