Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: revision-dynamo
      AttributeDefinitions:
      - AttributeName: CharacterName
        AttributeType: S
      KeySchema:
      - AttributeName: CharacterName
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '5'
