Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: revision-dynamo
      AttributeDefinitions:
      - AttributeName: CharacterName
        AttributeType: S
      - AttributeName: Power
        AttributeType: S
      KeySchema:
      - AttributeName: CharacterName
        KeyType: HASH
      - AttributeName: Power
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
