Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: revision-dynamo
      AttributeDefinitions:
        - AttributeName: CharacterName
          AttributeType: S
        - AttributeName: Power
          AttributeType: S
      KeySchema:
        - AttributeName: CharacterName
          KeyType: HASH
        - AttributeName: Power
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: Index1
          KeySchema:
            - AttributeName: CharacterName
              KeyType: HASH
            - AttributeName: Power
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: Index2
          KeySchema:
            - AttributeName: CharacterName
              KeyType: HASH
            - AttributeName: Power
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: Index3
          KeySchema:
            - AttributeName: CharacterName
              KeyType: HASH
            - AttributeName: Power
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: Index4
          KeySchema:
            - AttributeName: CharacterName
              KeyType: HASH
            - AttributeName: Power
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: Index5
          KeySchema:
            - AttributeName: CharacterName
              KeyType: HASH
            - AttributeName: Power
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
