Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "CodeBuildRevisionServiceRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: "codebuild.amazonaws.com" }
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AWSCodeCommitReadOnly"

  # https://docs.aws.amazon.com/dtconsole/latest/userguide/concepts.html#concepts-api
  NotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: codebuildrule
      DetailType: FULL
      EventTypeIds:
        - "codebuild-project-build-state-succeeded"
      Resource: !GetAtt Project.Arn
      Status: ENABLED
      Targets:
        - TargetType: SNS
          TargetAddress: "arn:aws:sns:eu-west-3:935529178062:revision-topic"

  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: revision-codebuild
      ConcurrentBuildLimit: 1
      Description: revision code build
      ServiceRole: !Ref ServiceRole
      #Triggers:
      #  BuildType: BUILD
      #  Webhook: true
      LogsConfig:
        CloudWatchLogs:
          GroupName: "codebuild"
          Status: "ENABLED"
          StreamName: "revision"
      Artifacts:
        Type: S3
        Location: revision-codebuild-935529178062
        Name: build-artifact.zip # / if packaging none to put the file directly
        Packaging: ZIP
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Type: CODECOMMIT
        Location: https://git-codecommit.eu-west-3.amazonaws.com/v1/repos/revision
        #Type: S3
        #Location: revision-codebuild-935529178062/src/
