Resources:
  #arn:aws:iam::935529178062:role/cdservicerole
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "codedeploy-revision"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: Allow
            Principal: { Service: ["codedeploy.amazonaws.com"] }
            Action: ["sts:AssumeRole"]
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda"

  AppServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: on-premise.yaml
      Parameters:
        ServiceRoleArn: !GetAtt Role.Arn

  AppLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambda.yaml
      Parameters:
        ServiceRoleArn: !GetAtt Role.Arn

  AppEC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        ServiceRoleArn: !GetAtt Role.Arn
